lootscraper.py
=> Catch unexpected errors and continue with next run

app/common.py, app/feed.py, app/scraper/info/utils.py, app/scraper/loot/amazon_prime.py, app/scraper/loot/gog.py, config.default.ini, lootscraper.py
=> Add gog giveaways support

app/scraper/info/igdb.py, app/scraper/info/steam.py, app/scraper/loot/amazon_prime.py, app/scraper/loot/epic_games.py, app/scraper/loot/gog.py, app/scraper/loot/steam.py, app/sqlalchemy.py, app/tools.py, app/upload.py, lootscraper.py
=> Use module specific loggers

app/scraper/loot/steam.py
=> Save text from Steam offer (for end date)

app/common.py, app/configparser.py, app/pagedriver.py, app/scraper/loot/humble.py, app/telegram.py, config.default.ini, lootscraper.py
(cherry picked from commit d788178189224eba6be816485bfde888e61c1f12)
=> Add support for Humble Bundle store

lootscraper.py
=> Do not search for titles already in the database

app/pagedriver.py, app/scraper/loot/amazon_games.py, app/scraper/loot/amazon_loot.py, app/scraper/loot/itch_games.py, app/scraper/loot/scraper.py
To use less RAM. Introduce scrolling for Amazon scrapers so that they still work.
=> Reduce scraper window to 1920 x 1200

README.md, app/common.py, app/configparser.py, app/scraper/loot/ios_games.py, app/scraper/loot/scraperhelper.py, app/telegram.py, config.default.ini
=> Add support for iOS games

app/telegram.py
=> Add Dismiss button to offers

app/telegram.py
=> Remove users that unregistered

app/telegram.py
=> Add new "duration" property to /status list

app/telegram.py
=> Move link in offers to button

app/scraper/loot/amazon_games.py
=> Fix amazon missing games (only first 15 or so were captured)

app/scraper/loot/amazon_games.py, app/scraper/loot/apple_games.py, app/scraper/loot/epic_games.py, app/scraper/loot/gog_games.py, app/scraper/loot/gog_games_alwaysfree.py, app/scraper/loot/google_games.py, app/scraper/loot/humble_games.py, app/scraper/loot/itch_games.py, app/scraper/loot/steam_games.py, app/scraper/loot/steam_loot.py
=> Fix Epic, unify required title

app/telegram.py
=> Add game title to loot

app/scraper/loot/amazon_loot.py, app/telegram.py
=> Fix for Amazon new page layout

Dockerfile
=> Add debug print of installed packages in Docker

alembic/versions/20221016_081844_inactive_users.py, app/sqlalchemy.py, app/telegram.py, lootscraper.py
=> Deactivate users who blocked the bot

README.md, alembic/versions/20221110_214822_channels.py, app/sqlalchemy.py, app/telegram.py
The bot admin now can add channels where the bot should post offers
=> Add support for Telegram channels

.github/workflows/publish_docker_hub.yml
=> Update dockerhub build for new develop branch

src/lootscraper/main.py, src/lootscraper/telegrambot.py
(cherry picked from commit 6d85eba43312c30e46a5bbaf8b49e0eb048364fd)
=> Log errors to Telegram

src/lootscraper/telegrambot.py
- Format errors as a code block / monospaced font
- Do not alert for common errors (network down for a while etc.)
=> Improve Telegram error handling

README.md, config.default.toml, src/lootscraper/common.py, src/lootscraper/scraper/loot/scraper.py, src/lootscraper/scraper/loot/scraperhelper.py, src/lootscraper/scraper/loot/ubisoft_games.py, tests/test_scraper.py
=> Add Ubisoft (Fix #54)

src/lootscraper/scraper/loot/itch_games.py
=> Fix excessive logging when itch.io game has no image

src/lootscraper/feed.py
=> Add Steam Genres to RSS feed

README.md, poetry.lock, pyproject.toml, src/lootscraper/html.py, src/lootscraper/processing.py
=> feat: add html gen

pyproject.toml, src/lootscraper/database.py, src/lootscraper/html.py, src/lootscraper/main.py, src/lootscraper/processing.py, src/lootscraper/telegrambot.py
=> feat: improve html views

tests/test_scraper.py
=> fix: fix broken tests

src/lootscraper/scraper/scraper_base.py, src/lootscraper/tools.py
=> fix: correctly identify demos

src/lootscraper/telegrambot.py
A mistake while refactoring led to new offers not being sent. At all :O. Now it's working again!
=> fix: new offers were not sent

src/lootscraper/database.py, src/lootscraper/processing.py, src/lootscraper/scraper/scraper_base.py
=> fix: gog confused claimable and always free games

src/lootscraper/scraper/scraper_base.py
Instead of `lootscraper.scraper.scraper_base` now show for example `lootscraper.scraper.amazon_games`.
=> feat: state module in logging message for scrapers

src/lootscraper/database.py, src/lootscraper/telegrambot.py
=> perf: optimize db access

src/lootscraper/main.py
Epic is the only source that has multiple schedules. This lead to executing it twice because at startup every schedule was executed once. Now every scraper is executed once only.
=> fix: stop epic games from being scraped twice at startup

Dockerfile, pyproject.toml
Update to Python 3.12 for app and Docker image.
=> chore: update python to 3.12

src/lootscraper/telegrambot.py
=> feat: only allow admins to control the bot in groups

src/lootscraper/scraper/amazon_base.py, src/lootscraper/scraper/amazon_games.py, src/lootscraper/scraper/amazon_loot.py
Amazon updated it's page layout again. The offer end dates are now shown on the details page and not on the overview...
=> fix: update amazon page layout

src/lootscraper/scraper/steam_base.py
Sometimes steam crashed because the "free" game ofer in the search results was not free after all. Didn't expect that. Now it's checked twice.
=> fix: stop crashing on invalid steam offers

src/lootscraper/processing.py, tests/test_gameinfo.py
=> fix: prefer exact matches

src/lootscraper/processing.py, src/lootscraper/scraper/amazon_games.py, tests/test_gameinfo.py
Use the separate page and not the carousel on the front page.
=> fix: make amazon game scraping more reliable

README.md, src/lootscraper/processing.py
=> feat: upload new "all" html pages

src/lootscraper/scraper/epic_games.py
=> fix: epic new page layout
